// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXZy6gC4ZiLR4gRcXt2oAbszC-qKZgv-s',
    appId: '1:213007028113:web:f100501061e7fc44465430',
    messagingSenderId: '213007028113',
    projectId: 'arab-contractors-news',
    authDomain: 'arab-contractors-news.firebaseapp.com',
    storageBucket: 'arab-contractors-news.firebasestorage.app',
    measurementId: 'G-MMWWP6K54J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsvVtCiT8waVS3rNuOZt67QWwxwxkK8qo',
    appId: '1:213007028113:android:7d7a0ed1db922998465430',
    messagingSenderId: '213007028113',
    projectId: 'arab-contractors-news',
    storageBucket: 'arab-contractors-news.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr0ZF3Urk69e9mGCFNcCM3_xGMJT-IHQA',
    appId: '1:213007028113:ios:c757c9e1df27db4c465430',
    messagingSenderId: '213007028113',
    projectId: 'arab-contractors-news',
    storageBucket: 'arab-contractors-news.firebasestorage.app',
    iosBundleId: 'com.example.arabContractors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr0ZF3Urk69e9mGCFNcCM3_xGMJT-IHQA',
    appId: '1:213007028113:ios:c757c9e1df27db4c465430',
    messagingSenderId: '213007028113',
    projectId: 'arab-contractors-news',
    storageBucket: 'arab-contractors-news.firebasestorage.app',
    iosBundleId: 'com.example.arabContractors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXZy6gC4ZiLR4gRcXt2oAbszC-qKZgv-s',
    appId: '1:213007028113:web:717b2e637a26e02c465430',
    messagingSenderId: '213007028113',
    projectId: 'arab-contractors-news',
    authDomain: 'arab-contractors-news.firebaseapp.com',
    storageBucket: 'arab-contractors-news.firebasestorage.app',
    measurementId: 'G-8NCS1TMCTP',
  );

}